# Theme
window_padding_width 2
font_features FiraCodeNF-Reg +ss03 # TODO: This is bad, will need to fix when Stylix supports it

# No close confirmation for commands
map f1 close_window_with_confirmation ignore-shell

# Bell Noise
enable_audio_bell no
